#
# Config for Site
#

# Name and Description of Site
title: Portfolio - Brandon Coffey
description: Portfolio - Brandon Coffey, Programmer and Technical Artist
author: Brandon Coffey
url: https://brandoncoffey.com

# Includes an icon in the footer for each username you enter
footer-links:
  email: business@brandoncoffey.com
  linkedin: brandon-coffey-36a802191
  artstation: brandon-coffey
  github: BrandonMCoffey
  stackoverflow:
  instagram:
  facebook:
  twitter:
  youtube:

collections:
  projects:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

permalink: /:title/

# Kramdown for Markdown
kramdown:
  # GitHub flavored markdown
  input: GFM
  # rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory
sass:
  style: :expanded # Or minify using :compressed

# Excluded files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
